use super::*;

#[test]
fn context_builder_time_warp_fails_closed() {
    use crate::state::{
        CardInfo as Sc, DangerFlags, DangerLevel, MonsterInfo, NormalizedState, PowerInfo,
    };

    let state = NormalizedState {
        screen_type: Some(crate::state::ScreenType::None),
        room_type: None,
        character: None,
        seed: None,
        ascension_level: None,
        floor: None,
        current_hp: Some(50),
        max_hp: Some(50),
        gold: None,
        energy: Some(0),
        block: None,
        powers: vec![],
        hand: vec![
            Sc {
                id: "Strike_R".into(),
                name: "打击".into(),
                cost: 0,
                card_type: "ATTACK".into(),
                upgraded: false,
                uuid: Some("tw-s1".into()),
                description: "造成 3 点伤害。".into(),
                price: None,
                playable: true,
                has_target: true,
            },
            Sc {
                id: "Strike_R".into(),
                name: "打击".into(),
                cost: 0,
                card_type: "ATTACK".into(),
                upgraded: false,
                uuid: Some("tw-s2".into()),
                description: "造成 3 点伤害。".into(),
                price: None,
                playable: true,
                has_target: true,
            },
            Sc {
                id: "Strike_R".into(),
                name: "打击".into(),
                cost: 0,
                card_type: "ATTACK".into(),
                upgraded: false,
                uuid: Some("tw-s3".into()),
                description: "造成 3 点伤害。".into(),
                price: None,
                playable: true,
                has_target: true,
            },
            Sc {
                id: "Strike_R".into(),
                name: "打击".into(),
                cost: 0,
                card_type: "ATTACK".into(),
                upgraded: false,
                uuid: Some("tw-s4".into()),
                description: "造成 3 点伤害。".into(),
                price: None,
                playable: true,
                has_target: true,
            },
        ],
        monsters: vec![MonsterInfo {
            name: "Time Eater".into(),
            monster_id: None,
            index: 0,
            current_hp: Some(10),
            max_hp: Some(10),
            block: Some(0),
            intent: None,
            damage: None,
            hits: None,
            monster_powers: vec![PowerInfo {
                id: "Time Warp".into(),
                name: "Time Warp".into(),
                amount: 0,
            }],
            can_be_killed: false,
            is_scaling: false,
        }],
        card_reward_choices: vec![],
        boss_relic_choices: vec![],
        event_id: None,
        event_name: None,
        event_body: None,
        event_choices: vec![],
        relics: vec![],
        potions: vec![],
        deck_names: vec![],
        incoming_damage: 0,
        rest_options: vec![],
        danger: DangerFlags {
            hp_critical: false,
            incoming_lethal: false,
            no_block_against_hit: false,
            any_monster_attacking: false,
            wrath_stance: false,
            level: DangerLevel::Safe,
        },
        skip_available: false,
        hand_cards: vec![],
        draw_pile: vec![],
        discard_pile: vec![],
        exhaust_cards: vec![],
        master_cards: vec![],
        map_nodes: vec![],
        map_first_node_chosen: None,
        map_current_x: None,
        map_current_y: None,
        shop_cards: vec![],
        shop_relics: vec![],
        shop_potions: vec![],
        purge_available: false,
        purge_cost: None,
        hand_select_max_cards: None,
        hand_select_can_pick_zero: false,
        hand_select_selected: vec![],
        current_action: None,
        card_in_play: None,
        grid_cards: vec![],
        grid_selected_cards: vec![],
        grid_for_upgrade: false,
        grid_for_transform: false,
        grid_for_purge: false,
        grid_num_cards: None,
        empty_potion_slots: 0,
        ..Default::default()
    };

    // 4 Strike cards (3 dmg each) vs 10hp, but Time Warp present → fail closed
    assert!(!can_end_fight(&state));
    assert!(find_kill_sequence(&state).is_none());
}
