use serde::{Deserialize, Serialize};

use super::{
    CardInfo, DangerFlags, MapCoord, MonsterInfo, OrbInfo, PotionInfo, PowerInfo, RelicInfo,
    RoomType, ScreenType,
};

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct NormalizedState {
    pub screen_type: Option<ScreenType>,
    pub room_type: Option<RoomType>,
    pub room_phase: Option<String>,
    pub character: Option<String>,
    pub seed: Option<i64>,
    pub ascension_level: Option<i64>,
    pub floor: Option<i64>,
    pub current_hp: Option<i64>,
    pub max_hp: Option<i64>,
    pub gold: Option<i64>,
    pub energy: Option<i64>,
    pub block: Option<i64>,
    pub powers: Vec<PowerInfo>,
    pub hand: Vec<CardInfo>,
    pub monsters: Vec<MonsterInfo>,
    pub card_reward_choices: Vec<CardInfo>,
    pub boss_relic_choices: Vec<RelicInfo>,
    pub event_id: Option<String>,
    pub event_name: Option<String>,
    pub event_body: Option<String>,
    pub event_choices: Vec<String>,
    pub relics: Vec<RelicInfo>,
    pub potions: Vec<PotionInfo>,
    pub deck_names: Vec<String>,
    pub incoming_damage: i64,
    pub rest_options: Vec<String>,
    pub danger: DangerFlags,
    pub skip_available: bool,
    pub shop_cards: Vec<CardInfo>,
    pub shop_relics: Vec<RelicInfo>,
    pub shop_potions: Vec<PotionInfo>,
    pub purge_available: bool,
    pub purge_cost: Option<i64>,
    pub turn_number: Option<i64>,
    pub orbs: Vec<OrbInfo>,
    pub stance: Option<String>,
    pub hand_cards: Vec<CardInfo>,
    pub draw_pile: Vec<CardInfo>,
    pub discard_pile: Vec<CardInfo>,
    pub exhaust_cards: Vec<CardInfo>,
    pub master_cards: Vec<CardInfo>,
    pub map_nodes: Vec<MapCoord>,
    pub map_first_node_chosen: Option<bool>,
    pub map_current_x: Option<i64>,
    pub map_current_y: Option<i64>,
    pub hand_select_max_cards: Option<i64>,
    pub hand_select_can_pick_zero: bool,
    pub hand_select_selected: Vec<CardInfo>,
    pub current_action: Option<String>,
    pub card_in_play: Option<CardInfo>,
    pub grid_cards: Vec<CardInfo>,
    #[serde(default)]
    pub grid_selected_cards: Vec<CardInfo>,
    pub grid_for_upgrade: bool,
    pub grid_for_transform: bool,
    pub grid_for_purge: bool,
    pub grid_num_cards: Option<i64>,
    pub empty_potion_slots: usize,
}
